version: "3"
services:
  microservice_container:
    # if failure  or server restarts, container will restart
    restart: always 
    container_name: microservice_container
    image: microservice_img
    ports:
      - "5000:5000"
    build: 
      context: .